title: 문과생을 위한 Copilot Studio
description: 문과생도 따라하는 Copilot Studio 실습 가이드
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://hyjung904.github.io
baseurl: /newcopilotstudiolab

aux_links:
  GitHub Repo: https://github.com/hyjung904/newcopilotstudiolab

nav_enabled: true
search_enabled: true
heading_anchors: true
color_scheme: light
